// <auto-generated />
namespace TravelTester.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_table_user_order_new : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_table_user_order_new));
        
        string IMigrationMetadata.Id
        {
            get { return "202003010053092_create_table_user_order_new"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
