// <auto-generated />
namespace TravelTester.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _202002210552114_update_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202002210552114_update_column));
        
        string IMigrationMetadata.Id
        {
            get { return "202002210600411_202002210552114_update_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
